#@URL=http://192.168.30.64/api/express/leituras
@URL=http://localhost:3000/leituras
### CREATE
POST {{URL}}
Authorization: 123123
Content-Type: application/json

{
    "idSensor": "s2",
    "tipoSensor": "temperatura",
    "leitura": "35"
}

### GET ALL
GET {{URL}}
Authorization: 123123

### GET BY ID
GET {{URL}}/68efe898e8562b397015b968
Authorization: 123123

### UPDATE
PUT {{URL}}/68efe898e8562b397015b968
Authorization: 123123
Content-Type: application/json

{
    "idSensor": "123456789",
    "tipoSensor": "temperatura",
    "leitura": "32.5 °C"
}

### DELETE 
DELETE {{URL}}/68efe898e8562b397015b968
Authorization: 123123